### ISSUE TITLE
keyboard colors are not correct sometimes

### ISSUE THREAD

**Issue by boxy-boy** [Epicpkmn11/WordleDS#1]
for example, if you have a black e and a yellow e on the same word (not sure if it happens across words), the keyboard's e will remain black. in the original wordle, any colored letters will color the corresponding letters on your keyboard.

**Comment by Epicpkmn11** [comment]
Oh whoops, it was always setting the keys every single time that letter was used, instead of just if it was a better color. Should be fixed be ed447a3, I'll probably make a v1.0.1 in a bit.
