### ISSUE TITLE
[Feature request] Timer + total time in QR

### ISSUE THREAD

**Issue by spellboundtriangle** [Epicpkmn11/WordleDS#15]
It would be nice if there were an optional timer to display while playing, that starts when the first character is pressed. You would also be able to have your total time as part of the QR code.

Another thing to add would maybe be something relating to past statistics, like your average completion time.

**Comment by Epicpkmn11** [comment]
Added an optional time to the results in b640b6cd50e1c4878b4f7c52904b8419e58afa37. I'll add it to the GUI settings, stats screen, and maybe add some other options like including the streak in the share message in a bit. For now open this once and open close settings to make it update the file, then edit `"timer"` to `true` in `sd:/_nds/WordleDS/settings.json`.

> Wordle DS 411 6/6 03:25
> 
> ⬜⬜⬜🟨🟨
> 🟩🟨⬜⬜⬜
> 🟩⬜⬜⬜🟩
> 🟩⬜⬜⬜🟩
> 🟩⬜⬜🟨🟩
> 🟩🟩🟩🟩🟩
