### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by StephanKuwabara** [Epicpkmn11/WordleDS#17]
Hi, I've installed the CIA release using the QR Code provided on Releases (version 2.1.0).  None of the touch keyboard keys seem to do anything, except for the enter key.  The settings window seems to work fine, the help window works fine as well.  I can tap the enter key and it'll tell me that the word is not in the word list; but I can't enter any letters.  Either I've done something wrong, or there's potentially an issue.

I've also tried using the NDS version, and I'm having the same issue there.  I'm doing this on a New Nintendo 3DS.

**Comment by Epicpkmn11** [comment]
Huh... That's really odd, maybe try deleting the `sd:/_nds/WordleDS` folder to see if that does anything.

You could maybe try using the [nightly version](https://nightly.link/Epicpkmn11/WordleDS/workflows/build/main/build.zip), though I'm not sure why that would affect anything.

**Comment by StephanKuwabara** [comment]
hmm, it didn't seem to help.  After clearing out that folder, it seems to crash (or at least put it into sleep mode) on first boot.  Then after that whenever I open the game, the keyboard is dead.  If there's supposed to be a set of empty letter grids on the top screen, those aren't showing either.  The top screen just has WORDLE DS, with a grey underline, and nothing else.

**Comment by Epicpkmn11** [comment]
Huh... Yeah there should be the letter grid, this is how it looks on load after closing the how to play screen:

![Wordle DS main gameplay screen](https://db.universal-team.net/assets/images/screenshots/wordle-ds/main-menu.png)

I don't have a DS on me to test, but it works fine for me in no$gba on a fresh SD image... Until the latest update it was crashing if I loaded it from GodMode9i, but I fixed the bug there so not sure what's up with it for you... I'll see if I can reproduce it on my 3DS when I can.

**Comment by Epicpkmn11** [comment]
Probably fixed by 0218a210978ca334efb6046f891b49ff55ca26a7, let me know if this is still an issue for you. Might also want to fix your clock if so ;P

**Comment by StephanKuwabara** [comment]
I forgot that I'd never changed this 3DS from it's default clock.  That makes perfect sense, since there would be no Wordle posted in 2011, lol.  Thank you for sorting that out for me!
