### ISSUE TITLE
[Suggestion] Add support for other languages

### ISSUE THREAD

**Issue by arthurbambou** [Epicpkmn11/WordleDS#2]

**Comment by Epicpkmn11** [comment]
I don't have plans to add other languages myself, however I've designed it to be fairly easy to edit so if you want to make a fork in another language feel free.

It was missing proper support for anything beyond ASCII, but as of e5b7e40358a780763e9757407504b755a4a29224 it should be relatively trivial to add support for other languages.

(ex. Added É and Ê)
![ss](https://user-images.githubusercontent.com/41608708/156526664-c41b573b-ce86-431d-a32e-e6172db138d8.png)
 
I've put some basic instructions on where to edit [in the README](https://github.com/Epicpkmn11/WordleDS#customizing) and I'm happy to help if needed.
