### ISSUE TITLE
Can't download words on DSi with WPA-2 connections

### ISSUE THREAD

**Issue by j0lol** [Epicpkmn11/WordleDS#25]
Getting a very similar behavior to this commenter: https://github.com/Epicpkmn11/WordleDS/issues/23#issuecomment-2027938345

**Comment by spellboundtriangle** [comment]
Wordle DS currently only supports DS-compatible Wi-Fi connections (WEP or no security, 802.11b)

**Comment by j0lol** [comment]
ah, thanks

**Comment by Epicpkmn11** [comment]
Added in d37aef1dac703dcc61a8658617c37b4a3c4150be
