### ISSUE TITLE
Hard Mode not functioning as intended

### ISSUE THREAD

**Issue by rdtoi1** [Epicpkmn11/WordleDS#4]
![20220318_141837](https://user-images.githubusercontent.com/93745449/159070734-75e05fc8-d779-4e6c-8507-f15075dd6b24.jpg)

**Comment by Epicpkmn11** [comment]
Did you exit and reopen mid-game? If so this should be fixed by cb0794b, if not then I'm not sure what's bugged as it seems to be working besides that for me...

**Comment by rdtoi1** [comment]
Yeah, I did
