### ISSUE TITLE
Another issue with hard mode

### ISSUE THREAD

**Issue by rdtoi1** [Epicpkmn11/WordleDS#6]
showcasing the issue with the march 20th word
![wordle](https://user-images.githubusercontent.com/93745449/159590083-97a81758-c573-4ca2-ad9e-83b2dbd85c35.png)
From what I can tell this only happens with repeat letters when you have the letter as green in one spot and yellow in another

**Comment by Epicpkmn11** [comment]
Whoops, I swear I tried to test it xD

Should be fixed by dcc8fc5.
