### ISSUE TITLE
how do i clear my data/streak?

### ISSUE THREAD

**Issue by fuglord** [Epicpkmn11/WordleDS#7]

**Comment by Epicpkmn11** [comment]
Delete `WordleDS.json`, it should be next to the ROM, but it may also be in the SD root depending on how it's loaded.

You can also just delete specific items from the JSON such as the `streak` or `maxStreak` if you want.

(In the current release it's already formatted human readably, but I changed it to be minified to not waste space so in future versions/nightlies can use sites such as http://jsonprettify.com to make it more readable fyi)
