### ISSUE TITLE
[feature request] Refresh button

### ISSUE THREAD

**Issue by lifehackerhansol** [Epicpkmn11/WordleDS#9]
A way to refresh would be nice. Especially after another day passes so we can refresh to a new word.

~~I just left my DS in sleep mode, turned it back on and it was still on yesterday's word~~

**Comment by Epicpkmn11** [comment]
Added in 8de9d429e4e6e799453888bb195b0e9b1002cc41

![refresh](https://user-images.githubusercontent.com/41608708/162564694-5d10771e-ca1a-453b-8c08-ad642c2b89ef.png)
Just click the refresh button and it'll reload the game, can still finish the previous day if you want as long as you don't click the refresh button.
